### ISSUE TITLE
About the computation complexity

### ISSUE THREAD

**Issue by ycjing** [liuzechun/ReActNet#1]
Hi @liuzechun 

Thank you for the nice paper and code! The work is really impressive. I have a quick question: how you compute the BOPs and FLOPs so as to obtain the OPs in Fig. 1? Thank you! 

Best,
Yongcheng

**Comment by liuzechun** [comment]
Hi Yongcheng,

Thanks for your interest in our work! The BOPs and FLOPs are the number of binary operations and floating-point operations in the network, respectively. For example, a 64, 64, 33, weight kernel convolving with a 64, 64, 3232 feature map will produce 64643332*32 BOPs (if it is a binary convolution) or FLOPs (if it is a real-valued convolution).

Hope this answer solves your question.

Thanks,
Zechun

**Comment by ycjing** [comment]
Hi @liuzechun 

Thank you so much for the quick response! I appreciate it. So for Fig. 1 in the paper, the OPs of all the models are computed manually? If this is the case, I know that there are some tools to compute FLOPs. May I ask is there any tools or libraries to automatically compute BOPs? Thank you! Wish you all the best!

Best,
Yongcheng

**Comment by liuzechun** [comment]
Hi Yongcheng,

I wrote the python code for calculating the OPs. I didn't use any library, maybe you can try to use the library for FLOPs calculation and modify it to support BOPs? 

Thanks,
Zechun

**Comment by ycjing** [comment]
Hi @liuzechun 

Thank you! Do you have any plan to open source the code to compute BOPs? Thanks!

Best,
Yongcheng

**Comment by liuzechun** [comment]
Dear Yongcheng,

Thanks for the suggestion. I'll discuss it with my collaborators~

Best,
Zechun

**Comment by ycjing** [comment]
Hi Zechun,

Got it. I really appreciate your help! Thank you! Will cite your nice work in all my relevant future manuscripts. Wish you all the best!

Best,
Yongcheng

**Comment by liuzechun** [comment]
Dear Yongcheng,

Thank you for the nice words! :) 

All the best,
Zechun
