### ISSUE TITLE
Why use torch.sign()?

### ISSUE THREAD

**Issue by theqihao** [liuzechun/ReActNet#11]
Hi, @liuzechun , your code use the torch.sign() to binary the weights and activations, I think the output of torch.sign() has three value（-1，0，1），as belows:
>>> a=torch.tensor([-1,-0,0,1])
>>> torch.sign(a)
tensor([-1,  0,  0,  1])

Could I think you use three numbers instead of two numbers?

**Comment by theqihao** [comment]
By the way, training_time is gotted by diving 36000, not 3600？

**Comment by BNAadministrator3** [comment]
I guess the 36000 should be corrected to 3600.

**Comment by feizi** [comment]
The probability of input(float32) being equal to 0 is very small. I think this may be the reason why the sign function works.

**Comment by liuzechun** [comment]
Hi, @theqihao thanks for your interest in our work! Sorry for my late reply! Yes, it should be 3600 instead of 36000, I updated the code. Thank you for letting us know. For the torch.sign(), what @feizi mentioned is correct. The floating-point numbers are very unlikely to be exactly 0.
