### ISSUE TITLE
binary convolution's weight are not -1or 1.

### ISSUE THREAD

**Issue by yuxianzhi** [liuzechun/ReActNet#12]
I see code https://github.com/liuzechun/ReActNet/blob/master/mobilenet/2_step2/reactnet.py#L67 find that binary convolution's weight is not -1 or 1. they are real value. this is different from birealnet.

after binary activation, the convolution's input are -1 or 1, the convolution's weight are -1/1 * scale, Is this similar with int8 quantization? we can extract scale process after convolution,

**Comment by liuzechun** [comment]
Hi, I uploaded the model with weights stored as exactly -1 and +1 to this repo, replacing the previous models. Please kindly check! The scaling factor can be absorbed in the batch norm layer. So when we store the weights as -1 and +1, we only need to recalculate the BN layer by training the network with weights fixed for one epoch. More theoretical proof can be found in Bi-Real Net paper(https://arxiv.org/pdf/1811.01335.pdf) Sec.3.4.2. Thanks!
