### ISSUE TITLE
param shape error of Model-ReAct-ResNet 

### ISSUE THREAD

**Issue by ustczwq** [liuzechun/ReActNet#14]
The torchsize of **fc layer** of resnet_based model should be **1000 × 512**, but in the trained [Model-ReAct-ResNet](https://hkustconnect-my.sharepoint.com/:u:/g/personal/zliubq_connect_ust_hk/EZAJ5OPNyKJColmmJPkD-ysBP2uozsXMzbbA9giOuS21TA?e=vb5bVq) you provided, it is **1000 × 1024**，which leads to loading error.

**Comment by Ironteen** [comment]
I found the same problem, I think the parameters of Model-ReAct-ResNet is the same as  Model-ReAct-MobileNet.

**Comment by liuzechun** [comment]
Hi, I have uploaded the new model to correct this mistake.
