### ISSUE TITLE
About the learnerable bias parameter

### ISSUE THREAD

**Issue by zz-cloud** [liuzechun/ReActNet#16]
How to acquire the learnerable parameters of Reign and RPrelu in detail?  The code provided is just to load  pretrained file. Thanks!!!

**Comment by ssw8** [comment]
I have the same question. And how would I acquire weights in binary? I tried calling using
`for param in modle_student.parameters():
      print(param.data)
`
and received everything in real values. 
Please kindly advise, thank you very much.

**Comment by liuzechun** [comment]
Hi, thanks for your interest in our work. The weights are binarized in the forward pass. You can load the weights, binarize them following the weight binarization function and store the model. Then load the model and do the inference, it will give you the same accurcay as reported.
