### ISSUE TITLE
Could you share  ResNet_34 model with ReAct binary you have been trained ?

### ISSUE THREAD

**Issue by puhan123** [liuzechun/ReActNet#18]
I do the work about binary object detection , and I need the pretrained model ResNet_34 on ImageNet, 

but train the binary model need a lot of time, Could you share  ResNet_34 model with ReAct binary method you have been trained ?

Thank you very much!

**Comment by liuzechun** [comment]
Hi, thanks for following our work. 

But we didn't run the experiments on ResNet-34 and we don't have the binary ResNet-34 models. 

Sorry for my late reply. Let me know if there's anything else I can help.
