### ISSUE TITLE
Question about flops

### ISSUE THREAD

**Issue by TIEHua** [liuzechun/ReActNet#19]
Sorry to bother you. We used **flops-counter** to calculate the Flops of ReActNet, and the result is 0.28x10^8, which is higher than 0.12x10^8 in the original paper. How do you calculate the Flops? 
Thanks for your time. I am waiting for your reply.

**Comment by liuzechun** [comment]
Thanks for your interest in our work. We calculate the FLOPs with the formula FLOPs = in_channel * out_channel * feature_map_width * feature_map_height * kernel_size * kernel_size, and OPs = FLOPs + BOPs/64. If the flops counter is targeted at floating-point operations, it may not consider the binarization into the calculation.

**Comment by HatemSelim94** [comment]
> Thanks for your interest in our work. We calculate the FLOPs with the formula FLOPs = in_channel * out_channel * feature_map_width * feature_map_height * kernel_size * kernel_size, and OPs = FLOPs + BOPs/64. If the flops counter is targeted at floating-point operations, it may not consider the binarization into the calculation.

@liuzechun Thank you for your answers and your great work. I have a question about the reported OPS. When calculating Bobs, convolution layers are the only layers considered and In FLOPS calculation, other layers such as (Batch norm, activation, skip connections, ...) are considered, is that correct? 
Thank you for your time.
