### ISSUE TITLE
Excuse me , why is your conv3x3 not DW conv?

### ISSUE THREAD

**Issue by loganyan** [liuzechun/ReActNet#2]
I remember the groups of con3x3(dw_conv) of original MobleNet are equal to the numbers of input channel.
What precision can be achieved if DW convolution is used?

**Comment by liuzechun** [comment]
Yes, the original MobileNet uses dw conv. And as we mentioned in our paper, we design the ReActNet based on MobileNet, change dw conv to vanilla conv and calculate the OPs accordingly. We didn't try dw conv for ReActNet, which may lead to divergence issue as we mentioned in one of our previous work (https://arxiv.org/abs/2005.06305).

Thanks,
Zechun

**Comment by loganyan** [comment]
Thank you for your answer！
