### ISSUE TITLE
Question about Reduction Block structure in reactnet

### ISSUE THREAD

**Issue by xvyaward** [liuzechun/ReActNet#20]
Hello, thanks for your great work and code.

I have a question about your reduction block structure design in react-mobilnet.

In the paper, each of the branches (that receives duplicated activations) has its own RSign and RPReLU modules like the below image.

![image](https://user-images.githubusercontent.com/32446763/139621323-3a215b93-ed70-4ce8-8820-630453071aca.png)

However, it seems that your code adjusts a single RSign module, and then duplicate activation. Also, the code concatenates each branch's activation first and then applies unified one RPReLU module.

So which version is correct? or there is not much difference for both accuracy?

Thanks for reading my question.

**Comment by liuzechun** [comment]
Hi, thanks for your interest in our work. The two implementations of separating the branches before/after the RSign module are mathematically equivalent. You can imagine the RSign with 2n channels = concatenate the output from 2 RSigns with n channels.
