### ISSUE TITLE
Some questions in the code

### ISSUE THREAD

**Issue by THKIM-CAS** [liuzechun/ReActNet#24]
First of all, thank you for sharing your job in public. My questions on your code are as follows:

1.  Your codes consist of two steps. Step 1: binarize activation only, Step 2: binarize both activation and weight. In training the model w.r.t. Step 2, the model is initialized based on the model trained from Step 1. (via checkpoint_ba.pth.tar) Why? Isn't it possible to train the model w.r.t. Step 2 from scratch?
2. The train is based on knowledge distillation; however, the soft label is not used at all. Why?
3. Could you share how long did it take to train the model on your workstation? My training lasts for several days ...

**Comment by liuzechun** [comment]
Hi, thanks for your interest in our work! 
For the questions
1. Yes, the Step 2 can be trained from scratch but initializing it with the model trained from Step 1 can achieve higher accuracy.
2. Soft labels are used by KD_loss.
3. It takes ~3 days on our workstation too.
Hope that solves your question.
Thanks!
