### ISSUE TITLE
Has anyone successfully trained on cifar10/100 dataset?

### ISSUE THREAD

**Issue by ThisisBillhe** [liuzechun/ReActNet#25]

**Comment by echoEric** [comment]
I tried to train same model in this code on cifar10 dataset but, I got about 80% of accuracy... How about you?

**Comment by ThisisBillhe** [comment]
> I tried to train same model in this code on cifar10 dataset but, I got about 80% of accuracy... How about you?

80% is a little low, I think the reason is that model designed for ImageNet may not be suitable for cifar. I got 56.39% on resnet20 1w1a on cifar100 dataset.

**Comment by liuzechun** [comment]
Hi, thanks for your interest in our work. We didn't try it on CIFAR dataset. I think the downsampling strategy in MobileNet may not work so well on CIFAR dataset, for which the image size is 32 x 32.
