### ISSUE TITLE
blocks where input_channels are bigger than output_channels

### ISSUE THREAD

**Issue by rainyBJ** [liuzechun/ReActNet#28]
When dealing with blocks where input_channels are smaller than output_channels in MobileNetV1, as mentioned in the paper, we duplicate the input and **concatenate** the output of every branch, so we can still benefit from the skip connection in each branch. But what about inverted-residual blocks in MobileNetV2 where input_channels are bigger than output_channels, can I just split the input channels(so that input&output channels are the same in each branch), and do similar ops for each branch and **add** them at output? Or we can't simply use this ReAct(RPreLU, RSign, Duplicate/Split channels to benefit from skip connections) idea to different network structures?

**Comment by liuzechun** [comment]
Hi, thanks for this interesting question. PreLU, RSign are agnostic to the network structures. Duplicating the channel size is restricted to the scenario that the downsampling layers have twice the number of channels. But you can always try to extend this idea by doing what you suggested and see whether it enhances the accuracy.

**Comment by rainyBJ** [comment]
Thanks for your reply! I'll do some related experiment in the future :)
