### ISSUE TITLE
Are the parameters of trained model actually float32 type? 

### ISSUE THREAD

**Issue by youngboy52** [liuzechun/ReActNet#5]
I found that the model size is still large, and the parameters of trained model are float type. How to save model's weights in int type to reduce the model size. Does the effect of quantization only result in reference part? 
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/15629424/96071271-55300c80-0ed4-11eb-9c56-70ee7fc8ecd4.png">

**Comment by liuzechun** [comment]
Hi, Thanks for the question. In training a BNN model, we use the real-valued latent weights to accumulate the gradient. And in the inference time (as well as the forward pass of the training phase), we use the binarized weight and activations, by taking the sign of the real-valued weights. Hope this explanation answers your question.
