### ISSUE TITLE
Error occurred in loading resnet model.

### ISSUE THREAD

**Issue by BobZhang321** [liuzechun/ReActNet#6]
Hi:
Size mismatch error occurred when I load the resnet model. Is it a step1 model?
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/27174291/96444284-97dd4600-1240-11eb-831a-fae75f2cf56e.png">

**Comment by liuzechun** [comment]
Hi, it is a step2 model.

**Comment by chartain02** [comment]
hi i am also facing this same issue...can you tell me how should i resolve this....we have only weight for 2nd step i guess
